### ISSUE TITLE
Header doesn't load on any platform

### ISSUE THREAD

**Issue by greberg** [maykar/custom-header#266]
A copy/paste of your Custom Header config (found in "Raw Config Editor" or ui-lovelace.yaml):
```
custom_header:
  compact_mode: true
  voice_hide: true
  exceptions:
    - conditions:
        #user_agent: Mobile
        user_agent: "CrKey"
      config:
        kiosk_mode: true
        show_tabs:
          - 'home_cast'
          - 'calendar_cast'
          - 'power_cast'
          - 'lights_cast'
          - 'media_cast'
          - 'location_cast'
          - 'garden_cast'
    - conditions:
        #user_agent: Mobile
        user_agent: "Home Assistant"
        media_query: "(max-width: 600px)"
      config:
        show_tabs:
          - 'home_mobile'
          - 'calendar_mobile'
          - 7
          - 'power_mobile'
          - 13
          - 15
          - 18
          - 21
          - 24
          - fan_mobile
          - 27
          - 30
          - 33
        default_tab: 'home_mobile'
    - conditions:
        user: 'name'
      config:
        show_tabs:
          - 0
          - 3
          - 6
          - 9
          - 12
          - 14
          - 17
          - 20
          - 23
          - 26
          - 29
          - 32
          - 35
          - 37 to 43
        default_tab: 'home_desktop'
```
Any errors relevant to Custom Header found in the HA logs:
Logger: frontend.js.latest.202009180
Source: components/system_log/__init__.py:193
First occurred: 23 september 2020 19:09:37 (33 occurrences)
Last logged: 9:58:00

https://url/hacsfiles/custom-header/custom-header.js:1:14666 Uncaught TypeError: e[o].trim is not a function
https://url/hacsfiles/custom-header/custom-header.js:1:14670 TypeError: e[o].trim is not a function. (In 'e[o].trim()', 'e[o].trim' is undefined)

Any relevant errors found in your browsers dev console (F12):
Uncaught TypeError: e[o].trim is not a function
    at processTabArray (custom-header.js:1)
    at Function.processAndContinue (custom-header.js:146)
    at unsub.subscribeRenderTemplate.template (custom-header.js:146)
    at Object.r.subscribeMessage.type [as callback] (custom-header.js:1)
    at o._handleMessage (core.1af90ed7.js:1)
    at WebSocket.<anonymous> (core.1af90ed7.js:1)

The version of Home Assistant and Custom Header you are using
HA: 0.115.2 Custome Header: 1.7.9
The browsers or apps that are affected (i.e. Firefox, Chrome, Chrome Mobile, iOS HA Companion app, etc.)
Chrome and iOS HA Companion app
Installation method (HACS or manual)
Hacs
HA config method (YAML or Storage). If you don't know what this means, you're using Storage mode
YAML

**Comment by RomRider** [comment]
Same issue here with `hide_tabs`. If removed from the config, it works well.

**Comment by maykar** [comment]
Please, give the latest release (1.8.0) a try and report back.

**Comment by greberg** [comment]
Yes works fine with 1.8.0. Thank you
